version: '3.9'
services:
  db-mysql-master-1:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - db-mysql-master-1-data:/var/lib/mysql
      - ./group.master.cnf:/etc/mysql/mysql.conf.d/group.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - SERVER_ID=1
    networks:
      default:
        aliases:
          - mysql-master-1
    restart: always
  db-mysql-slave-1:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - db-mysql-slave-1-data:/var/lib/mysql
      - ./group.slave.1.cnf:/etc/mysql/mysql.conf.d/group.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      default:
        aliases:
          - mysql-slave-1
    depends_on:
      - db-mysql-master-1
    restart: always
  db-mysql-slave-2:
    image: mysql:5.7
    expose:
      - "3306"
    volumes:
      - db-mysql-slave-2-data:/var/lib/mysql
      - ./group.slave.2.cnf:/etc/mysql/mysql.conf.d/group.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      default:
        aliases:
          - mysql-slave-2
    depends_on:
      - db-mysql-master-1
    restart: always
  maxscale:
    image: mariadb/maxscale:6.3.0
    ports:
      - 8989:8989
      - 4006:4006
      - 4008:4008
    volumes:
      - ./maxscale.cnf:/etc/maxscale.cnf
      # 文件名只能是 maxscale.cnf 其他文件名无法被读取
      - ./custom-maxscale.cnf:/etc/maxscale.cnf.d/maxscale.cnf
    depends_on:
      - db-mysql-master-1
      - db-mysql-slave-1
      - db-mysql-slave-2
    restart: always
    networks:
      default:
        aliases:
          - maxscale
networks:
  default:
    name: mysql-cluster-network
    ipam:
      # driver: overlay
      config:
        - subnet: 172.28.0.0/16
volumes:
  db-mysql-master-1-data:
  db-mysql-slave-1-data:
  db-mysql-slave-2-data:
